### ISSUE TITLE
Kalibrierung 

### ISSUE THREAD

**Issue by AaronStra** [kenogo/ComptonScattering#2]
Die Kalibrierung für das Cs137 Spektrum passt noch nicht ganz.
Der Peak müsste bei 662 keV liegen.
Ich kümmer mich drum

**Comment by kenogo** [comment]
Weiß nicht was du meinst, tut er doch...

**Comment by kenogo** [comment]
Ach ne gerade gesehen. Stimmt da ist unten irgendwas faul

**Comment by kenogo** [comment]
Ah ok der Fehler liegt einfach bei `channel_to_energy`. Die Funktion macht gerade genau das Gegenteil von dem was sie machen sollte...

**Comment by AaronStra** [comment]
Korrektur mit     return 1/calibration[0]*(channel-calibration[1])
klappt

**Comment by kenogo** [comment]
Behoben durch https://github.com/kenogo/ComptonScattering/commit/cfb67f7b74a9e72a9c3093e55dd7ce85c41020f7
