### ISSUE TITLE
Unsicherheiten Peaks

### ISSUE THREAD

**Issue by AaronStra** [kenogo/ComptonScattering#3]
Ich würde eher die Standardabweichung der Gausfits als Unsicherheiten angeben als die Unsicherheiten im Mittelwert

**Comment by kenogo** [comment]
Das halte ich nicht für richtig. Die Standardabweichung der Gaußfits bezieht sich ja darauf, mit welcher Wahrscheinlichkeit ein einzelner Messwert aus einem Zerfall innerhalb der Gaußbreite liegt. Sie bezieht sich nicht darauf, wo der Peak tatsächlich ist.

**Comment by AaronStra** [comment]
Die Breite der Gaußpeaks spiegelt aber die Genauigkeit wieder mit der der Detektor überhaupt den Energiewert auflösen kann. Vergleichst du die ermittelte Genauigkeit mit der angestrebten Linearität des Bin-Energieverhältnisses müssten die Fehler 100x größer sein als die, die wir jetzt haben.

**Comment by kenogo** [comment]
Ja ok ich kümmer mich dann mal darum.

**Comment by AaronStra** [comment]
Ich habe auch darüber nachgedacht und bin mir nicht 100% sicher, aber ich würde so argumentieren, dass wir ja auch wenn wir eine Stichprobe mit vielen Messungen machen, die den gleichen Wert ergeben sollen, eine Gaußkurve drüber legen könnten und sagen könnten so, der Fehler ist der Fehler des Mittelwertes aus der Gaußkurve. Aber wir nehmen ja dann schon die Standardabweichung...

**Comment by kenogo** [comment]
Ja also ich denk eigentlich echt dass der Fehler des Mittelwerts ausm Fit das ist, was wir verwenden sollten. Ansonsten würde ein längeres Messen mit besserer Statistik ja auch unsere Fehler kaum minimieren. Aber ich bin jetzt zu müde um darüber zu diskutieren. Also entweder ich mach das jetzt so und beim Abtestat musst du argumentieren, oder ich lass es so und ich muss es verteidigen :D

**Comment by AaronStra** [comment]
Dann ehrlich gesagt lieber mit Standardabweichung

**Comment by kenogo** [comment]
Ja ok mach ich sobald ich alles mit dem Wirkungsquerschnitt fertig hab. Zum Glück beeinflusst das ja eigentlich nur den Graphen von der Kallibrierung.... Wobei mir gerade auffällt, dass wir dann etwas andere Gewichte haben und deswegen vielleicht bei der Kallibrierung ein bisschen was anderes rauskommt. Also mache ich das wohl doch lieber jetzt...

**Comment by kenogo** [comment]
Ist mittlerweile erledigt
