### ISSUE TITLE
Background Smoothing

### ISSUE THREAD

**Issue by AaronStra** [kenogo/ComptonScattering#5]
Das Smoothing des Backgrounds sieht zwar nice aus,
glaube aber als Leser vermutet man, dass wir damit versuchen irgendeinen
physikalischen Sachverhalt zu zeigen. Daher würde ich es lieber weglassen.

**Comment by kenogo** [comment]
Der physikalische Sachverhalt, den ich im Kopf hatte, ist dass das Rauschen auf unserem Signal nur zufällig ist, und sich unser Zufallsfehler verdoppeln würde, wenn wir dieses Rauschen noch von unserem ohnehin verrauschtem Signal abziehen.

**Comment by AaronStra** [comment]
Ok klingt gut
