### ISSUE TITLE
Korrektur Compton

### ISSUE THREAD

**Issue by AaronStra** [kenogo/ComptonScattering#7]
Habe die Compton-Kontinuen linear gefittet,
würde sagen, dass das zeigt, dass es vernachlässigbar ist und nicht weiter analysieren...

![compton_fit1](https://user-images.githubusercontent.com/28979330/33630982-6a5121ce-da09-11e7-83ae-2abc39acc817.png)
![compton_fit2](https://user-images.githubusercontent.com/28979330/33630983-6a73f67c-da09-11e7-927b-2c9a2c68c5bb.png)

**Comment by kenogo** [comment]
Ja find ich gut danke
