### ISSUE TITLE
Compton Wirkungsquerschnitt

### ISSUE THREAD

**Issue by AaronStra** [kenogo/ComptonScattering#8]
Für den Comptonwirkungsquerschnitt muss glaube ich die Fläche unter der Gaußkurve ins Verhältnis gesetzt werden. Wenn in beiden Fällen die Standardabweichung die gleiche ist (wie es aussieht) reicht dann aber auch das Verhätlnis der Maxima.

**Comment by kenogo** [comment]
Ja die Standardabweichung muss auch gleich sein da es ja bei der selben Energie ist. Sie würde nur anders groß sein, wenn man beachtet, dass schon Compton gestreute Photonen noch gemessen werden. Allerdings wäre es in dem Fall sogar trotzdem besser, das Maximum zu nehmen, weil diese bereits gestreuten Photonen die Fläche unterm Peak mehr verändern als das Maximum.

**Comment by AaronStra** [comment]
stimmt, macht sinn wir messen ja wirklich nur: wie viele kamen vorher ohne zu streuen an--> wie viele kommen jetzt ohne zu streuen an ---> Rest streut, OK
